[package]
name = "avs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethers = "2.0.0"
eyre = "0.6.12"
serde = "1.0.203"
tokio = { version = "1.38.0", features = ["full"] }
