[tool.poetry]
name = "py"
version = "0.1.0"
description = ""
authors = ["idatsy <stefan@ranvier.co.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
web3 = "^6.19.0"
aiostream = "^0.6.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
